### PR TITLE
Update to csproj by vs2017

### PR DESCRIPTION
**Pull request by kleberksms**

### CODE REVIEW

**Comment by kleberksms** [comment]
image

**Comment by SapientGuardian** [comment]
I've actually already done this in #52, I just haven't merged it in - mostly because I was hoping it would fix #51 but it didn't, and I haven't had the time to figure out why.

**Comment by kleberksms** [comment]
ok, I'll try to fix https://github.com/SapientGuardian/SapientGuardian.EntityFrameworkCore.MySql/issues/51

**Comment by SapientGuardian** [comment]
Cool, thanks! It's probably ok to merge #52 even if we can't fix #51 with it, but that'd be great if you could figure out what I missed there.

**Pull request closed without merging**
